# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: EnvironmentVariables

steps:
- script: echo $(keyVaultName)
  displayName: 'Show variable(s)'

#- script: az --version
#  displayName: 'Show Azure CLI version'
  
#- script: az upgrade --yes
#  displayName: 'Upgrade Azure CLI version if needed'

#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'ARM'
#    scriptType: 'pscore'
#    scriptLocation: 'scriptPath'
#    scriptPath: '01 - ResourceGroup.ps1'
#    arguments: '-rgName $(rgName) -defaultLocation $(defaultLocation)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARM'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: '02 - StorageAccount.ps1'
    arguments: '-rgName $(rgName) -storageAccountName $(storageAccountName)'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARM'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: '03 - KeyVault.ps1'
    arguments: '-rgName $(rgName) -keyVaultName $(keyVaultName)'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARM'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: '04 - AzureDataFactory.ps1'
    arguments: '-rgName $(rgName) -ADFName $(ADFName)'