# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev_us-east-1
- name: sub_name
  value: 'Microsoft Azure Enterprise'

steps:
- script: |
    echo $REGION
    echo $SUBSCRIPTIONNAME
    echo $REGION
    echo $(sub_name)
  displayName: 'Show Variable Values'