# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: EnvironmentVariables
- name: project_name
  value: "foo"

steps:
- script: |
    echo $defaultLocation
    echo $DEFAULTLOCATION
    echo $(defaultLocation)
  displayName: 'Show variables'

#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'ARM'
#    scriptType: 'pscore'
#    scriptLocation: 'inlineScript'
#    inlineScript: |
#      Write-Host "The value of project_name is $env:project_name"

#- script: az --version
#  displayName: 'Show Azure CLI version'
  
#- script: az upgrade --yes
#  displayName: 'Upgrade Azure CLI version if needed'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARM'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'ParameterTest.ps1'
    arguments: '-rgName $(rgName)'