# Pipeline for Databricks cluster creation

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - pipelines/config.cluster.json
    - pipelines/databricks-library-install.sh

stages:
- stage: "dev"
  displayName: "Development"
  dependsOn: []
  pool:
    vmImage: "ubuntu-latest"
  variables:
    - group: databricks_cli

  jobs:
    - job: CreateCluster4Dev
      steps:

        - task: UsePythonVersion@0
          inputs:
            versionSpec: "3.8"
            architecture: "x64"

        - task: ShellScript@2
          inputs:
            scriptPath: brick-cli-config.sh
            args: "$(databricks_host) $(databricks_token)"
          displayName: "Install and configure the Databricks CLI"

#        - task: ShellScript@2
#          inputs:
#            scriptPath: pipelines/databricks-cluster-delete.sh
#            args: "HelloCluster"
#          continueOnError: "true"
#          displayName: "Delete previous cluster version (if existing)"

#        - task: ShellScript@2
#          inputs:
#            scriptPath: pipelines/databricks-cluster-create.sh
#            args: "HelloCluster"
#          displayName: "Create new cluster"

#        - task: ShellScript@2
#          inputs:
#            scriptPath: pipelines/databricks-library-install.sh
#            args: "HelloCluster"
#          displayName: "Install Python and R dependencies"
